### ISSUE TITLE
REQUEST: New/alter membership - Víctor Mayoral-Vilches as Reviewer

### ISSUE THREAD

**Issue by vmayoral** [ros-security/community#25]
### Request
- Upgrade privileges as Reviewer

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more projects under the ROS 2 Security Working Group

### Sponsors (if applicable)
- Xilinx

### List of contributions to ROS 2 Security Working Group
- Various, long term ROS and security contributor

**Comment by vmayoral** [comment]
@artivis, @ruffsl, @mikaelarguedas, I'm looking to help re-spin the group's activity (*in a similar fashion to what we're doing with the Hardware Acceleration WG, which has kept a ~30 participants the past 4 meetings, mostly from industry*). To that end, I'm asking to change my privileges.

**Comment by vmayoral** [comment]
Connected to https://github.com/ros-security/community/pull/24

**Comment by mikaelarguedas** [comment]
:+1: Happy to see that regardless of the company you're involved with you keep bringing so much good stuff to the field of security in robotics !

**Comment by artivis** [comment]
Another +1 for a freshly appointed approver.

**Comment by ruffsl** [comment]
:+1: from me!

**Comment by artivis** [comment]
Congrats on upgrading to reviewer!
