### ISSUE TITLE
REQUEST: New/alter membership - artivis as Approver

### ISSUE THREAD

**Issue by artivis** [ros-security/community#26]
### Request
Requesting a role upgrade from *reviewer* to *approver*.

There are currently no active *approver* resulting in PRs stacking up.

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more projects under the ROS 2 Security Working Group

### Sponsors (if applicable)
- Canonical

### List of contributions to ROS 2 Security Working Group
- Various contributions to sros2
- Currently co-drive the WG

**Comment by vmayoral** [comment]
I thought you owned the org rights @artivis! Of course, +1 to this.

**Comment by kyrofa** [comment]
:+1: from me.

**Comment by artivis** [comment]
@mikaelarguedas Any chance to get yours eyes on this application since such change requires unanimous agreement from approvers?

**Comment by mikaelarguedas** [comment]
:+1:

As you say most/all original approvers are not very active, maybe it would make sense to demote some (me included) to avoid clogging the process

**Comment by kyrofa** [comment]
Confirmed, @artivis is now an Approver. Congratulations, @artivis!
