### ISSUE TITLE
REQUEST: New/alter membership - Ruffin White as Approver

### ISSUE THREAD

**Issue by ruffsl** [ros-security/community#30]
### Request
- Upgrade privileges as Approver

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more projects under the ROS 2 Security Working Group

### List of contributions to ROS 2 Security Working Group
- https://github.com/ros2/sros2/graphs/contributors
- https://github.com/ros-swg/moveit2_demo/graphs/contributors
- https://github.com/ros-swg/turtlebot3_demo/graphs/contributors

**Comment by vmayoral** [comment]
+1 for this. @mikaelarguedas do you think you could make a similar ask yourself?

**Comment by artivis** [comment]
+1 :+1:

**Comment by mikaelarguedas** [comment]
+1 :+1:

**Comment by mikaelarguedas** [comment]
> mikaelarguedas do you think you could make a similar ask yourself

:+1: https://github.com/ros-security/community/issues/31

**Comment by artivis** [comment]
On second thought, why do you apply for 'reviewer' and not directly for 'approver' @ruffsl ??

**Comment by ruffsl** [comment]
> On second thought, why do you apply for 'reviewer' and not directly for 'approver' @ruffsl ??

Ok, I can do that. I have updated this ticket to reflect this.

**Comment by artivis** [comment]
Welcome to the 'approvers' ruffsl!
