### ISSUE TITLE
REQUEST: New/alter membership: downgrade Mikael Arguedas to reviewer

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-security/community#31]
### Request
- Downgrade privileges to Reviewer

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I am actively contributing to 1 or more projects under the ROS 2 Security Working Group

### List of contributions to ROS 2 Security Working Group
- https://github.com/ros2/sros2/graphs/contributors
- https://github.com/ros-swg/turtlebot3_demo/graphs/contributors

**Comment by vmayoral** [comment]
Let’s get Mikael privileges please!

**Comment by artivis** [comment]
+1 to this, but I ain't happy about it ;)

**Comment by artivis** [comment]
Done.
